---
- name: Install Ansible Host Baseline
  hosts: all
  become: true
  vars_files:
    - "{{ playbook_dir }}/vars/base.yml"
  tasks:
    - name: Build container image
      tags: build
      ansible.builtin.include_tasks:
      file: "{{ playbook_dir }}/jobs/build/{{ item }}.yml"
      apply:
        tags:
        - build
      loop:
      - libraries
      - user

    - name: run and execute runtime tasks for container
      tags:
        - run
      block:
        - name: Include networking
          ansible.builtin.include_tasks:
            file: "{{ playbook_dir }}/jobs/run/networking.yml"
            apply:
              tags:
                - run
